### ISSUE TITLE
When XIV is running on the secondary monitor in Windows 11 the countdown displays on the main monitor.

### ISSUE THREAD

**Issue by Lunatory** [xorus/EngageTimer#21]
I've tried adjusting the offset to match my main (left) monitor's size but that pushes the number offscreen into the void rather than on the intended secondary (right) window where XIV is running. Other plugins with similar pop-up windows do not have this issue.

**Comment by xorus** [comment]
That's because the offset actually just extends the invisible window. 
It would seem a window cannot span multiple monitors then ^^.
I will try to find a way to make it work when I have time to dev after Xmas but it doesn't seem easy. Maybe with an option to freely move the big timer (but without centering) ? Hmm.

**Comment by Lunatory** [comment]
Turning off Dalamud's "Enable multi-monitor windows" option has fixed the issue.

**Comment by xorus** [comment]
The latest version will allow you to place the countdown on your second monitor :).
It does have some caveats though for now:
- You must use the offset sliders to move the window (as before)
- A black background will appear behind the countdown (this is a dalamud limitation)

It is only available in my repo for now, but I will publish it soon though when I'm 100% sure it's stable!
