### ISSUE TITLE
Feature request: potion window notification

### ISSUE THREAD

**Issue by Flavescent** [xorus/EngageTimer#53]
Hi, thank you for this very useful plugin!

I'd appreciate the option to have the timer flash (e.g. blink and change color) at configurable intervals (e.g. from 06:00 to 06:20) into a fight. The use case for this would be to notify the player that it is time to use a potion in a high-end duty.

**Comment by xorus** [comment]
That could be a good feature and something I missed when I was raiding!

Here's the implementation plan I was thinking:

```
in configuration ui:
[Stopwatch]
Alarm at :
- [ 6:00 ] for [ 30s ] [-]
- [+]

With [-] to remove, [+] to add a new one to the list

Alarm mode : 
[ x ] blink
[ x ] change color [ color picker here ]
Maybe an option to play a sound ?
```

in code:
- On framework update, add a thing that would set the state of the stopwatch to blinking mode depending on the configuration and current time. To not kill performance as this is array traversal it should not run each frame but max once per second.
- In stopwatch ui: implement blinking mode

No guarantees on when I can implement this, it could take me anywhere from a few days to a month, I'm very busy with life at the moment but I'll definitely try!

**Comment by Flavescent** [comment]
Thank you for looking into it! Playing a configurable sound (e.g. <se.2>) would be nice. Maybe even the option to change the timer text into some other text (e.g. "Potion!"). This would allow players to set fight-specific reminders (e.g. "Look away from boss!").

**Comment by xorus** [comment]
I can't really do text because of the way I load the font with a custom size. If a user sets the size to like 48pt the font texture altas usually is not big enough to contain more than 0-9 number characters.
If I were to do text I'd need to compromise by having it being default dalamud-text size (or with a choice on the list of already loaded fonts) and I guess on a new line below the stopwatch.

**Comment by xorus** [comment]
Still working on it @Flavescent, it's taking some time sorry!
Before that, I've been rewriting parts of the plugin to optimize stuff, which delayed this. 
I have not forgotten though, life got in the way <.<

**Comment by xorus** [comment]
Found a way to add text! It can also print to /echo chat.
Now the hardest part is to make an actually usable gui to configure it.

https://github.com/xorus/EngageTimer/assets/2473314/2e2592c4-9b2a-4e77-8c96-ccac73171c5e

**Comment by xorus** [comment]
It's available on my testing repository!
You can try it by adding `https://plogon.xorus.dev/` to your plugin repo list and searching for engage timer dev version - don't forget to disable the original one first.

Since this comes with a pretty big rewrite of the whole plugin I have a bit to test before I can release it globally.
